name: Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r doc/wiki/requirements.txt

    - name: Build documentation
      run: |
        cd doc/wiki
        make html

    - name: Deploy to Read the Docs
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "" https://readthedocs.org/api/v3/projects/gLPU/versions/latest/build/
