# readthedocs.yml

version: 2

sphinx:
  configuration: doc/wiki/source/conf.py

python:
  install:
    - requirements: doc/wiki/requirements.txt

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
