site_name: gLPU
site_description: Documentation repository for the gLPU project
site_url: https://glpu.gesslar.dev
site_author: gesslar
nav:
  - Home: index.md
  - FluffOS: https://fluffos.info
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate

plugins:
  - macros
  - search

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Help:
      - Environment Variables: environment_variables/index.md
  - Systems:
      - Daemons: systems/daemons.md
      - GMCP: systems/gmcp.md
      - GMCP Specification: systems/gmcp_specification.md
  - Functions:
      - Simul Efuns: simul_efun/index.md
      - Overridden Efuns: efun_override/index.md
      - Daemon Functions: daemon_function/index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  constants:
    MUD_NAME: "gLPU"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gesslar/gLPU
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wzUbBgs3AQ

copyright: Copyright &copy; Shmopyright
