site_name: gLPU
site_description: Documentation repository for the gLPU project
site_url: https://glpu.gesslar.dev
site_author: gesslar
nav:
  - Home: index.md
  - FluffOS: https://fluffos.info
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to automatic mode

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

plugins:
  - macros
  - search

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  constants:
    MUD_NAME: "gLPU"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gesslar/gLPU
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wzUbBgs3AQ

copyright: Copyright &copy; Shmopyright

extra_css:
  - stylesheets/extra.css

### This section is for the navigation
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Features:
    - Preferences:
      - User: features/preferences/user.md
      - Administrator: features/preferences/administrator.md
    - GMCP:
      - Overview: features/gmcp/gmcp.md
      - Specification: features/gmcp/gmcp_specification.md
  - Daemons:
    - daemons/index.md
    - Alarm: daemons/alarm.md
    - Autodoc: daemons/autodoc.md
    - Boot: daemons/boot.md
    - Config: daemons/config.md
    - Loot: daemons/loot.md
    - GitHub Issues: daemons/github_issues.md
    - Signal: daemons/signal.md
  - Modules:
    - modules/index.md
    - Daemon:
      - modules/daemon/index.md
    - Standard:
      - modules/std/index.md
      - modules/std/currency.md
      - modules/std/loot.md
    - Living:
      - modules/living/index.md
      - modules/living/race.md
  - Functions:
    - functions/index.md
    - Simulated Efuns: functions/simul_efun/index.md
    - Efun Override: functions/efun_override/index.md
    - Daemon Functions: functions/daemon_function/index.md
