name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          cd doc/wiki
          npm install

      - name: Build VitePress site
        run: |
          cd doc/wiki
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email "karahd@gmail.com"
          git config --global user.name "gLPU Automation"

      - name: Deploy to GitHub Pages
        run: |
          cd doc/wiki/docs/.vitepress/dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:${{ github.repository }}.git main:gh-pages
