name: CI and Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'doc/wiki/**'
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - name: Checkout game repository
      uses: actions/checkout@v2
      with:
        path: 'game'

    - name: Capture game directory path
      id: capture-game-dir
      run: echo "GAME_DIR=$(pwd)/game" >> $GITHUB_ENV

    - name: Checkout FluffOS
      uses: actions/checkout@v4
      with:
        repository: 'fluffos/fluffos'
        path: 'fluffos'

    - name: Capture FluffOS directory path
      id: capture-fluffos-dir
      run: echo "FLUFFOS_DIR=$(pwd)/fluffos" >> $GITHUB_ENV

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf automake bison expect libmysqlclient-dev libpcre3-dev libpq-dev libsqlite3-dev libssl-dev libtool libz-dev telnet libgtest-dev libjemalloc-dev

    - name: Compile FluffOS
      working-directory: fluffos
      env:
        CC: "gcc"
        CXX: "g++"
      run: |
        cp ${{ env.GAME_DIR }}/adm/etc/local_options.github ${{ env.FLUFFOS_DIR }}/local_options
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DPACKAGE_UIDS=OFF -DPACKAGE_MUDLIB_STATS=OFF ..
        VERBOSE=1 make -j `nproc` install


    - name: Replace placeholders in config.github
      run: |
        sed -i "s|{{GAME_DIR}}|${{ env.GAME_DIR }}|g" game/adm/etc/config.github

    - name: Build Docs
      run: |
        ./fluffos/build/bin/driver game/adm/etc/config.github -fbuilddocs

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r game/doc/wiki/requirements.txt

    - name: Build documentation
      run: |
        cd game/doc/wiki
        make html

    - name: Deploy to Read the Docs
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "" https://readthedocs.org/api/v3/projects/gLPU/versions/latest/build/
